resolver: nightly-2016-10-10
packages:
- '.'
- location: '../../'
  subdirs:
    - 'yi-core'
    - 'yi-frontend-pango'
    - 'yi-keymap-vim'
    - 'yi-misc-modes'
    - 'yi-mode-haskell'
extra-deps: []
