flags: {}
nix:
  shell-file: shell.nix
packages:
- yi-core
- yi-frontend-vty
# - yi-frontend-pango
- yi-fuzzy-open
- yi-keymap-cua
- yi-keymap-emacs
- yi-keymap-vim
- yi-mode-haskell
- yi-mode-javascript
- yi-misc-modes
- yi-ireader
- yi-language
- yi-snippet
# - yi
extra-deps: []
resolver: lts-8.18
build:
 library-profiling: false
 executable-profiling: false
