resolver: nightly-2016-10-21
packages:
- '.'
- location: '../../'
  subdirs:
    - 'yi-core'
    - 'yi-frontend-vty'
    - 'yi-keymap-vim'
    - 'yi-language'
    - 'yi-misc-modes'
    - 'yi-mode-haskell'
extra-deps:
- Hclip-3.0.0.4