resolver: nightly-2016-10-10
packages:
- '.'
- location: '../../'
  subdirs:
    - 'yi-core'
    - 'yi-frontend-vty'
    - 'yi-keymap-emacs'
    - 'yi-misc-modes'
    - 'yi-mode-haskell'
extra-deps: []
